name: Backtest V2 Train Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Validate pinned SHAs
        run: |
          set -e
          git ls-remote https://github.com/actions/checkout | grep 08c6903cd8c0fde910a37f88322edcfb5dd907a8
          git ls-remote https://github.com/actions/setup-python | grep a26af69be951a213d495a4c3e4e4022e16d87065
          git ls-remote https://github.com/actions/upload-artifact | grep ea165f8d65b6e75b540449e92b4886f43607fa02
          git ls-remote https://github.com/actions/download-artifact | grep 694cdabd8bdb022872a0656a84eb2e172f79dbb0

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib

      - name: Download backtest outputs
        uses: actions/download-artifact@694cdabd8bdb022872a0656a84eb2e172f79dbb0
        with:
          name: backtest_v2_diag_align
          path: _out_4u

      - name: List artifact files
        run: ls -R _out_4u

      - name: Train model
        run: |
          python - <<'PYCODE'
          import pandas as pd, joblib, os
          from sklearn.linear_model import LogisticRegression

          # find preds_test.csv dynamically
          preds_path, trades_path = None, None
          for root, _, files in os.walk("_out_4u"):
              if "preds_test.csv" in files:
                  preds_path = os.path.join(root, "preds_test.csv")
              if "trades.csv" in files:
                  trades_path = os.path.join(root, "trades.csv")

          if not preds_path or not trades_path:
              raise FileNotFoundError("preds_test.csv or trades.csv not found in downloaded artifact")

          preds = pd.read_csv(preds_path)
          trades = pd.read_csv(trades_path)

          if "label" not in preds.columns:
              if "y" in trades.columns:
                  preds["label"] = trades["y"]
              elif "label" in trades.columns:
                  preds["label"] = trades["label"]
              else:
                  preds["label"] = (preds["p_trend"] > 0.5).astype(int)

          features = [c for c in ["macd_hist","ofi","rsi","adx","p_trend","p_raw"] if c in preds.columns]
          if not features:
              raise RuntimeError("No valid features found in preds_test.csv")

          X = preds[features].fillna(0.0).to_numpy()
          y = preds["label"].astype(int).to_numpy()

          clf = LogisticRegression(max_iter=500)
          clf.fit(X, y)

          joblib.dump(clf, "conf/model.pkl")
          print("✅ Model trained and saved to conf/model.pkl")
          PYCODE

      - name: Upload model
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: trained-model
          path: conf/model.pkl
