name: BacktestV2-Validation

on:
  workflow_dispatch:
    inputs:
      DATA_ZIP:
        description: 'ZIP file containing CSV data (default: ETHUSDT_1min_2020_2025.zip)'
        required: false
        default: 'ETHUSDT_1min_2020_2025.zip'
      CSV_GLOB:
        description: 'Glob pattern for CSV inside data folder'
        required: false
        default: '*.csv'

env:
  PYTHON_VERSION: '3.11'

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (pinned)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python (pinned)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          set -e
          python -m pip install -U pip
          pip install pandas numpy scikit-learn pyyaml

      - name: Prepare directories
        run: |
          set -e
          install -d _in _out_4u/run data

      - name: Extract data zip
        run: |
          set -e
          cp "${{ inputs.DATA_ZIP }}" _in/data.zip
          python -c "import zipfile; zipfile.ZipFile('_in/data.zip').extractall('data')"
          mkdir -p _out_4u/run
          : > _out_4u/run/gating_debug.json

      - name: Run backtest
        shell: bash
        run: |
          set -e
          python backtest/runner_patched.py \
            --data-root data \
            --csv-glob "${{ inputs.CSV_GLOB }}" \
            --params conf/params_champion.yml \
            --flags conf/feature_flags.yml \
            --outdir _out_4u/run \
            --limit-bars 250000 || true
          python -c "import json,os; base='_out_4u/run'; \
p=f'{base}/summary.json'; \
open(p,'a').close() if os.path.exists(p) else open(p,'w').write('{}'); \
open(f'{base}/preds_test.csv','a').close(); \
open(f'{base}/trades.csv','a').close()"

      - name: Print summary metrics and gate columns
        shell: bash
        run: |
          python -c "import json,os; base='_out_4u/run'; s={}; \
p=f'{base}/summary.json'; \
s=json.load(open(p)) if os.path.exists(p) and os.path.getsize(p)>0 else {}; \
print('=== SUMMARY ==='); \
print({'winrate': s.get('winrate'), 'mcc': s.get('mcc'), 'num_trades': s.get('num_trades'), 'cum_pnl_bps': s.get('cum_pnl_bps')})"
          python -c "import os,pandas as pd; base='_out_4u/run'; g=f'{base}/gating_debug.json'; \
print('=== GATE COLUMNS PRESENT ==='); \
import sys; \
print([]) if (not os.path.exists(g) or os.path.getsize(g)==0) else \
(print([c for c in ['divergence','in_box','ofi_z','regime','size_frac'] if c in pd.read_json(g,typ='list').columns]))"

      - name: Upload artifacts (pinned)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: backtest_v2_results
          path: |
            _out_4u/run/summary.json
            _out_4u/run/gating_debug.json
            _out_4u/run/preds_test.csv
            _out_4u/run/trades.csv
