name: Backtest V2 Train Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib

      - name: Train model
        run: |
          python - <<'PYCODE'
          import pandas as pd, joblib
          from sklearn.linear_model import LogisticRegression
          preds = pd.read_csv("_out_4u/run/preds_test.csv")
          trades = pd.read_csv("_out_4u/run/trades.csv")
          if "label" not in preds.columns:
              preds["label"] = trades.get("y", (preds["p_trend"]>0.5).astype(int))
          features = [c for c in ["macd_hist","ofi","rsi","adx","p_trend","p_raw"] if c in preds.columns]
          X = preds[features].fillna(0.0).to_numpy()
          y = preds["label"].astype(int).to_numpy()
          clf = LogisticRegression(max_iter=500)
          clf.fit(X, y)
          joblib.dump(clf, "conf/model.pkl")
          print("Model saved to conf/model.pkl")
          PYCODE

      - name: Upload model
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: trained-model
          path: conf/model.pkl
