name: Backtest V2 Rerun

on:
  workflow_dispatch:
  workflow_call:

jobs:
  train:
    uses: ./.github/workflows/backtest_v2_train.yml

  rerun:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Validate pinned SHAs
        run: |
          set -e
          git ls-remote https://github.com/actions/checkout | grep 08c6903cd8c0fde910a37f88322edcfb5dd907a8
          git ls-remote https://github.com/actions/setup-python | grep a26af69be951a213d495a4c3e4e4022e16d87065
          git ls-remote https://github.com/actions/upload-artifact | grep ea165f8d65b6e75b540449e92b4886f43607fa02
          git ls-remote https://github.com/actions/download-artifact | grep refs/tags/v4
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: backtest_v2_diag_align
          path: .
      - name: Download model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: conf
      - name: Re-run backtest
        run: |
          set -e
          python backtest/runner_patched.py \
            --data-root data \
            --csv-glob '*.csv' \
            --params conf/params_champion.yml \
            --flags conf/feature_flags.yml \
            --calibrator conf/calibrator_bins.json \
            --outdir _out/final \
            --debug-level entries || true
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: backtest_v2_rerun
          path: _out/final
