name: CompareToSingle_V2_LOCAL
on:
  workflow_dispatch:
    inputs:
      CSV_GLOB:
        description: Data CSV glob
        default: "**/*ETHUSDT*1min*2020*2025*.csv"
        required: true
        type: string
      PY:
        description: Python version
        default: "3.11"
        required: true
        type: choice
        options: ["3.11","3.10"]
      CALIBRATOR:
        description: Optional calibrator JSON path
        default: ""
        required: true
        type: string

env:
  CODE_ZIP: strategy_v2_codepack_v2.1.3.zip
  DATA_ZIP: ETHUSDT_1min_2020_2025.zip

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ inputs.PY }}

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          pip install --upgrade pip
          pip install --prefer-binary "numpy<2.0" "llvmlite==0.42.*" "numba==0.59.*" "pandas<2.3" "scikit-learn<1.5" "pyyaml" || \
          pip install "numpy==1.24.4" "llvmlite==0.40.*" "numba==0.57.*" "pandas==1.5.3" "scikit-learn==1.2.2" "pyyaml"

      - name: Prep data/codepack
        shell: bash
        run: |
          set -euo pipefail
          unzip -q -o "$DATA_ZIP" -d data
          unzip -q -o "$CODE_ZIP" -d _codepack
          echo "PYTHONPATH=_codepack:_codepack/src:.:src" >> "$GITHUB_ENV"
          install -d out/A out/B

      - name: Run A (champion)
        shell: bash
        run: |
          set -euo pipefail
          CAL=""; [ -f "${{ inputs.CALIBRATOR }}" ] && CAL="--calibrator ${{ inputs.CALIBRATOR }}"
          python backtest/runner_patched_v2_iso.py --mode run \
            --data-root data --csv-glob "${{ inputs.CSV_GLOB }}" \
            --params conf/params_champion.yml --outdir out/A $CAL

      - name: Build params B
        shell: bash
        run: |
          set -euo pipefail
          python -c "import yaml; d=yaml.safe_load(open('conf/params_champion.yml')); d.setdefault('exit',{{}})['min_hold']=6; yaml.safe_dump(d, open('conf/params_alt.yml','w'))"

      - name: Run B (alt)
        shell: bash
        run: |
          set -euo pipefail
          CAL=""; [ -f "${{ inputs.CALIBRATOR }}" ] && CAL="--calibrator ${{ inputs.CALIBRATOR }}"
          python backtest/runner_patched_v2_iso.py --mode run \
            --data-root data --csv-glob "${{ inputs.CSV_GLOB }}" \
            --params conf/params_alt.yml --outdir out/B $CAL

      - name: Compare summaries
        shell: bash
        run: |
          set -euo pipefail
          python -c "import json; a=json.load(open('out/A/summary.json')); b=json.load(open('out/B/summary.json')); import sys; print(json.dumps({{'A':a,'B':b}}, indent=2)); open('out/compare_summary.json','w').write(json.dumps({{'A':a,'B':b}}, indent=2))"

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: compare_v2_local_${{ github.run_id }}
          path: |
            out/A
            out/B
            out/compare_summary.json
          if-no-files-found: error
